version: '3'

services:
   dev_db:
     image: mysql:5.7
     volumes:
       - dev_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: dev
       MYSQL_USER: dev
       MYSQL_PASSWORD: password
     ports:
      - "3306:3306"


volumes:
  dev_db_data: {}