version: '3'

volumes:
  dev_db: {}

services:
  dev_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - dev_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"